#!/bin/bash

# dependencies: git, tokei
# parameter: address of remote git repository

# This script clones a repository in a temporary directory and displays
# programming language statistics about it, and cleans up in the end.

if [ -z $1 ]
then
  SCRIPT=$(basename $0)
  printf "usage: ${SCRIPT} <repository address>\n"
  exit 1
fi

DESTREPO=/var/tmp/test-repo
[ -d $DESTREPO ] && rm -rf $DESTREPO 

git clone $1  $DESTREPO
tokei -s lines $DESTREPO 
[ -d $DESTREPO ] && rm -rf $DESTREPO 

